version: "3.9"
services: 
  postgresql: 
    container_name: "postgresql"
    image: postgres:13.3
    environment: 
      POSTGRES_DB: "goland"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "ienuShiavahZaeh0"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes: 
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports: 
      - "127.0.0.1:5432:5432"
    logging:
      driver: "gcplogs"
      options:
        gcp-log-cmd: "true"
        gcp-project: pyproject-334209
        env: DEV 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U admin -d goland"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy: 
      resources: 
        limits: 
          cpus: '1'
          memory: 2G
  monolith: 
    container_name: einstein-server
    image: ghcr.io/aevsai/einstein-server:latest
    restart: always
    env_file:
      - .env
    logging:
      driver: "gcplogs"
      options:
        gcp-log-cmd: "true"
        gcp-project: pyproject-334209
        env: PROD
#     healthcheck:
#      test: [ "CMD", "curl", "-f", "http://0.0.0.0:80/" ]
#      interval: 30s
#      timeout: 20s

networks: 
  default: 
    name: "goland-bridge"
#
